/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Aside: typeof import('./src/components/aside/index.vue')['default']
    copy: typeof import('./src/components/LaAside copy/index.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElTable: typeof import('element-plus/es')['ElTable']
    Handsontable: typeof import('./src/components/LaTable/handsontable.vue')['default']
    Header: typeof import('./src/components/header/index.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LaAside: typeof import('./src/components/LaAside/index.vue')['default']
    LaConfigProvider: typeof import('./src/components/LaConfigProvider/index.vue')['default']
    LaFooter: typeof import('./src/components/LaFooter/index.vue')['default']
    LaHeader: typeof import('./src/components/LaHeader/index.vue')['default']
    MyGrid: typeof import('./src/components/MyGrid.vue')['default']
    Provider: typeof import('./src/components/provider/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VxeTable: typeof import('./src/components/LaVxeTable/vxeTable.vue')['default']
  }
}
