/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElTable: typeof import('element-plus/es')['ElTable']
    Handsontable: typeof import('./src/components/LaTable/handsontable.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LaConfigProvider: typeof import('./src/components/LaConfigProvider/index.vue')['default']
    MyGrid: typeof import('./src/components/MyGrid.vue')['default']
    Provider: typeof import('./src/components/provider/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
